[theme]
base = "light"
primaryColor = "#000000"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F4F2"
textColor = "#2D2A26"
font = "sans serif"

[server]
maxUploadSize = 200

[browser]
gatherUsageStats = false
